-- ShopPilot biz-mock 模式基线（round18 票 42 / ADR 0041）
--
-- 本文件的 DDL 由 Hibernate 导出后人工审阅固化，不是手写方言。导出命令：
--
--   java -jar shoppilot-biz-mock/target/shoppilot-biz-mock-0.1.0-SNAPSHOT.jar \
--     --spring.main.web-application-type=none \
--     --shoppilot.bizmock.seed.enabled=false \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/schema-h2.sql
--
-- 导出后 DDL 内容逐字未改，只做了两件事：加了本注释块、把行尾从 CRLF 归一为 LF
-- （Hibernate 的脚本写出用平台行分隔符；迁移文件按 LF 入库）。可复算：
--
--   diff <(tail -12 .../db/migration/V1__baseline.sql | tr -d '\r') \
--        <(tail -12 target/schema-h2.sql | tr -d '\r')     # 无输出
--
-- 共 9 张表 / 3 个索引 / 1 个唯一约束。
--
-- 两点必须知道的口径：
--   1. 本文件是 H2 方言。orders.status 是 H2 原生 enum（Hibernate 6 对 @Enumerated(STRING)
--      在支持原生枚举的库上生成 enum 类型），Instant 一律是 timestamp(6) with time zone。
--      换库时这份基线要整体重导出，不能当可移植 DDL 用。
--   2. ddl-auto 已是 validate，本文件是模式的唯一产生源。实体上的 @Index 注解在 validate 下
--      不再被校验，已降级为文档；索引的真相源同样是本目录的迁移文件。

create table coupons (discount_fen bigint not null, id bigint generated by default as identity, threshold_fen bigint not null, status varchar(20) not null, customer_id varchar(32) not null, tenant_id varchar(32) not null, rule_id varchar(64) not null, primary key (id));
create table customers (phone varchar(20) not null, id varchar(32) not null, nickname varchar(64) not null, primary key (id));
create table feedback (created_at timestamp(6) with time zone not null, verdict varchar(8) not null, review_status varchar(12) not null, customer_id varchar(32) not null, tenant_id varchar(32) not null, id varchar(40) not null, ticket_id varchar(40), conversation_id varchar(64) not null, signals varchar(128), reason varchar(512), rule_ids clob, primary key (id));
create table logistics (seq integer not null, id bigint generated by default as identity, occurred_at timestamp(6) with time zone not null, cp_code varchar(32) not null, node_code varchar(32) not null, order_id varchar(32) not null, tenant_id varchar(32) not null, cp_name varchar(64) not null, tracking_no varchar(64) not null, description varchar(255) not null, primary key (id));
create table order_addresses (version integer not null, changed_at timestamp(6) with time zone not null, id bigint generated by default as identity, receiver_phone varchar(20) not null, city varchar(32) not null, district varchar(32) not null, order_id varchar(32) not null, province varchar(32) not null, tenant_id varchar(32) not null, receiver_name varchar(64) not null, detail_address varchar(255) not null, primary key (id));
create table orders (address_version integer not null, amount_fen bigint not null, created_at timestamp(6) with time zone not null, delivered_at timestamp(6) with time zone, paid_at timestamp(6) with time zone, shipped_at timestamp(6) with time zone, receiver_phone varchar(20) not null, category_code varchar(32) not null, city varchar(32) not null, customer_id varchar(32) not null, district varchar(32) not null, id varchar(32) not null, province varchar(32) not null, tenant_id varchar(32) not null, category_name varchar(64) not null, receiver_name varchar(64) not null, service_flags varchar(128) not null, detail_address varchar(255) not null, status enum ('CANCELLED','COMPLETED','CREATED','DELIVERED','PAID','REFUNDED','REFUNDING','SHIPPED') not null, primary key (id));
create table refunds (amount_fen bigint not null, created_at timestamp(6) with time zone not null, id bigint generated by default as identity, status varchar(20) not null, customer_id varchar(32) not null, order_id varchar(32) not null, tenant_id varchar(32) not null, idempotency_token varchar(64) not null, reason varchar(255) not null, primary key (id), constraint uk_refund_idempotency unique (order_id, idempotency_token));
create table tenants (rate_limit_qps integer not null, id varchar(32) not null, name varchar(64) not null, primary key (id));
create table tickets (created_at timestamp(6) with time zone not null, priority varchar(10), status varchar(20) not null, customer_id varchar(32) not null, tenant_id varchar(32) not null, id varchar(40) not null, reason varchar(40) not null, user_query varchar(512) not null, transcript clob not null, primary key (id));
create index idx_coupon_customer on coupons (customer_id);
create index idx_logistics_order on logistics (order_id);
create index idx_addr_order on order_addresses (order_id);
