-- round23 票 70：分流规则表 + SLA 计时（ADR 0055）
--
-- 规则表是数据不是代码：分派逻辑只认这张表，改队列/改 SLA 是一次数据变更，不是发版。
-- 通配用 '*' 表示（tenant_id / source / reason 三列都可能是通配）。
--
-- 匹配键为什么是「来源 + 降级原因」而不是 ADR 0055 字面写的「意图」：
-- 落单那一刻 intent 已经是 ESCALATE（AgentStateMachine.fallback 一律返回它），
-- 把原始意图接进落单请求要穿 21 个调用点，且拿到的多半不是买家真正要办的事。
-- 而「退款审批单该去 REFUND 队列、槽位问不齐的单该去 ESCALATION 队列」这件事，
-- 来源与降级原因就是它的直接答案，且两列都已经在工单上。偏离已登记在票 70 的 Handoff。
create table routing_rules (
    id bigint generated by default as identity,
    tenant_id varchar(32) not null,
    source varchar(24) not null,
    reason varchar(40) not null,
    queue varchar(32) not null,
    priority varchar(10) not null,
    sla_minutes integer not null,
    enabled boolean not null,
    updated_at timestamp(6) with time zone not null,
    updated_by varchar(32),
    primary key (id)
);

-- 初始规则。默认值刻意选得保守：默认队列 24 小时，规则表里每一行都可以被更具体的那行覆盖。
insert into routing_rules (tenant_id, source, reason, queue, priority, sla_minutes, enabled, updated_at, updated_by) values
    ('*', '*',            '*',                    'DEFAULT',    'normal', 1440, true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'DEGRADE',      'EMOTION_ESCALATION',   'ESCALATION', 'high',    60,   true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'DEGRADE',      '*',                    'ESCALATION', 'normal', 480,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'REFUND_APPROVAL', '*',                  'REFUND',     'money',   240,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'FEEDBACK_REVIEW', '*',                  'REVIEW',     'normal', 1440, true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'CHANNEL_RECEIPT',  '*',                 'REPLY',      'normal', 480,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed');

-- SLA 超时标记：只打戳，不改工单状态、不自动关单（ADR 0055 明确「不承诺解决时限」）。
alter table tickets add column escalated_at timestamp(6) with time zone;

-- 优先级口径换代：null 的旧含义是「不是情绪升级，按原口径排队」，等价于新枚举的 NORMAL。
-- 这是**语义等价回填**，不是改分母；存储字面量沿用既有契约（'high' 仍表示情绪升级，
-- verify-emotion.ps1 的活体判据逐字依赖它），枚举名 URGENT_EMOTION 是领域侧的叫法。
update tickets set priority = 'normal' where priority is null;