-- round23 票 71：审计事件落地（ADR 0054 / 0056）
--
-- 流里的是事件，表里的是「已经被消费掉的事件」。两者都要有：只有流，查历史要靠 XRANGE 扫；
-- 只有表，跨进程那条路就不成立。
--
-- event_id 唯一约束就是幂等的全部实现——投递语义是至少一次，去重放在唯一索引上，
-- 不放在应用层的「先查再插」（后者在并发下必然漏）。
create table audit_event (
    id bigint generated by default as identity,
    event_id varchar(64) not null,
    schema_version integer not null,
    action varchar(40) not null,
    object_type varchar(24) not null,
    object_id varchar(64) not null,
    tenant_id varchar(32) not null,
    actor varchar(32) not null,
    detail varchar(255),
    occurred_at timestamp(6) with time zone not null,
    consumed_at timestamp(6) with time zone not null,
    primary key (id),
    constraint uk_audit_event_id unique (event_id)
);

-- 查询面：按租户 + 时间倒序取「近期发生过什么」。审计是给近期查的，不是全量报表。
create index idx_audit_tenant_time on audit_event (tenant_id, occurred_at);