-- 工单与坐席服务的基线（round23 票 72 / ADR 0053、0055）
--
-- tickets 与 routing_rules 两张表从 biz-mock 搬到这里（所有者裁定 B：数据随服务走）。
-- 搬而不是共库的理由是物理的：H2 内存库在**进程内**，两个进程无法共享同一个库。
--
-- 表结构与 biz-mock 的 V3/V4 逐列一致（那段历史留在那边不动，那边的 V6 会把这两张表删掉），
-- 这里是从零重建，所以列定义写全。

create table tickets (
    created_at timestamp(6) with time zone not null,
    priority varchar(10),
    status varchar(20) not null,
    customer_id varchar(32) not null,
    tenant_id varchar(32) not null,
    id varchar(40) not null,
    reason varchar(40) not null,
    user_query varchar(512) not null,
    transcript clob not null,
    source varchar(24) not null,
    queue varchar(32),
    assignee varchar(32),
    sla_deadline timestamp(6) with time zone,
    escalated_at timestamp(6) with time zone,
    payload clob,
    primary key (id)
);

-- 规则表：分派规则是数据不是代码（ADR 0055）。通配用 '*' 表示。
create table routing_rules (
    id bigint generated by default as identity,
    tenant_id varchar(32) not null,
    source varchar(24) not null,
    reason varchar(40) not null,
    queue varchar(32) not null,
    priority varchar(10) not null,
    sla_minutes integer not null,
    enabled boolean not null,
    updated_at timestamp(6) with time zone not null,
    updated_by varchar(32),
    primary key (id)
);

-- 初始规则：与 biz-mock V4 播的六条逐字一致。搬迁不是改口径，所以两份种子必须相同；
-- 若将来两边规则表要各自演化，那是一件要重新裁决的事（现在它们是同一份规则的两次落地）。
insert into routing_rules (tenant_id, source, reason, queue, priority, sla_minutes, enabled, updated_at, updated_by) values
    ('*', '*',               '*',                  'DEFAULT',    'normal', 1440, true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'DEGRADE',         'EMOTION_ESCALATION', 'ESCALATION', 'high',    60,   true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'DEGRADE',         '*',                  'ESCALATION', 'normal', 480,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'REFUND_APPROVAL', '*',                  'REFUND',     'money',   240,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'FEEDBACK_REVIEW', '*',                  'REVIEW',     'normal', 1440, true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'CHANNEL_RECEIPT',  '*',                 'REPLY',      'normal', 480,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed');

-- 队列列表按「队列 + 优先级 + 时间」取件，这是坐席台的主查询。
-- 与 round18 票 43 的教训一致：这条索引必须有上界（按队列取件天然有），
-- 当年那条无上界的工单列表查询正是「有索引反而更慢」的原因（docs/slow-query-optimization-2026-09-21.md）。
create index idx_ticket_queue_order on tickets (queue, priority, created_at);