-- 工单与坐席服务的基线（PostgreSQL 方言，round28 票 100 / ADR 0061）
--
-- 本文件的 DDL 由 Hibernate 按 PostgreSQL 方言导出后人工审阅固化。导出命令（在模块目录下跑，
-- create-target 会**追加**写文件，重跑前必须先删旧产物）：
--
--   java -jar target/shoppilot-ticket-0.1.0-SNAPSHOT.jar \
--     --spring.main.web-application-type=none \
--     --spring.jpa.hibernate.ddl-auto=none \
--     --spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect \
--     --spring.jpa.properties.hibernate.default_schema=public \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/schema-pg.sql
--
-- 与 H2 基线的方言差（以导出产物为准）：
--   1. transcript / payload：H2 是 clob，PG 是 **oid（大对象）**——@Lob 在 PG 上的厂商默认落点。
--      试过 LONGVARCHAR（H2 validate 炸）与 LONG32VARCHAR（PG setNull(4001) 炸：Unknown Types
--      value），三选一只有 @Lob/oid 两侧全绿；「PG 落 text」连同实验矩阵登记在 ADR 0061。
--      代价：这两列只经 Hibernate 读写，pg_dump/恢复要带大对象（B2 备份演练的输入）；
--   2. 本文件是**现状全量**（含 V2 的 channel/contact 两列），不是 H2 V1 的历史态——
--      PG 从 2026-10-06 的现状一次性基线化，V2 是版本占位，保证两侧迁移版本钟同步，
--      下一个增量（V3 起）两库各落一份。
--
-- 相对导出产物的两处人工补齐（与 H2 V1 相同的两段，搬迁不是改口径，两侧种子逐字一致）：
--   a. routing_rules 的六条初始规则（Hibernate 导不出 INSERT）；
--   b. idx_ticket_queue_order 取件索引（H2 V1 的手工索引，实体注解没有它）。
--
-- 共 2 张表 / 1 个索引。ddl-auto 仍是 validate，本目录是 PG 侧模式的唯一产生源。

create table routing_rules (enabled boolean not null, sla_minutes integer not null, id bigint generated by default as identity, updated_at timestamp(6) with time zone not null, priority varchar(10) not null, source varchar(24) not null, queue varchar(32) not null, tenant_id varchar(32) not null, updated_by varchar(32), reason varchar(40) not null, primary key (id));
create table tickets (created_at timestamp(6) with time zone not null, escalated_at timestamp(6) with time zone, sla_deadline timestamp(6) with time zone, priority varchar(10), channel varchar(16), status varchar(20) not null, source varchar(24) not null, assignee varchar(32), customer_id varchar(32) not null, queue varchar(32), tenant_id varchar(32) not null, id varchar(40) not null, reason varchar(40) not null, user_query varchar(512) not null, payload oid, transcript oid not null, contact varchar(255), primary key (id));

insert into routing_rules (tenant_id, source, reason, queue, priority, sla_minutes, enabled, updated_at, updated_by) values
    ('*', '*',               '*',                  'DEFAULT',    'normal', 1440, true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'DEGRADE',         'EMOTION_ESCALATION', 'ESCALATION', 'high',    60,   true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'DEGRADE',         '*',                  'ESCALATION', 'normal', 480,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'REFUND_APPROVAL', '*',                  'REFUND',     'money',   240,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'FEEDBACK_REVIEW', '*',                  'REVIEW',     'normal', 1440, true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed'),
    ('*', 'CHANNEL_RECEIPT',  '*',                 'REPLY',      'normal', 480,  true, timestamp with time zone '2026-10-01 00:00:00+00', 'seed');

create index idx_ticket_queue_order on tickets (queue, priority, created_at);
