-- ShopPilot biz-mock 模式基线（PostgreSQL 方言，round28 票 100 / ADR 0061）
--
-- 本文件的 DDL 由 Hibernate 按 PostgreSQL 方言导出后人工审阅固化（B1 换库，H2 V1 文件头
-- 预告过的「换库时这份基线要整体重导出」）。导出命令（在模块目录下跑，create-target 会**追加**
-- 写文件，重跑前必须先删旧产物）：
--
--   java -jar target/shoppilot-biz-mock-0.1.0-SNAPSHOT.jar \
--     --spring.main.web-application-type=none \
--     --shoppilot.bizmock.seed.enabled=false \
--     --spring.jpa.hibernate.ddl-auto=none \
--     --spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/schema-pg.sql
--
-- 与 H2 基线的四处方言差，全部以导出产物为准：
--   1. orders.status：H2 是原生 enum，PG 是 varchar(20) + check 约束（Hibernate 6.5 对
--      @Enumerated(STRING) 在两库的落地不同，取值集合逐字一致）；
--   2. feedback.rule_ids：H2 是 clob，PG 是 **oid（大对象）**——@Lob 在 PG 上的厂商默认落点。
--      试过 LONGVARCHAR（H2 validate 炸：found clob / expecting text）与 LONG32VARCHAR
--      （PG setNull(4001) 炸：Unknown Types value），三选一只有 @Lob/oid 两侧全绿；
--      「PG 落 text」连同实验矩阵登记在 ADR 0061，不在 B1 强行换。
--      代价：这三类列只经 Hibernate 读写（全仓裸 SQL 不碰它们），pg_dump/恢复要带大对象（B2 备份演练的输入）；
--   3. users.role：与 orders.status 同理，varchar + check；
--   4. 本文件是**现状全量**（含 users / actor_authenticated / refunds.ticket_id），
--      不是 H2 V1 的 9 表历史态——PG 从 2026-10-06 的现状一次性基线化，V2-V8 是版本占位
--      （内容已并入本文件），保证两侧迁移版本钟永远同步，下一个增量（V9 起）两库各落一份。
--
-- 相对导出产物的两处人工补齐：
--   a. idx_audit_tenant_time：H2 V5 的手工索引，实体注解没有它，Hibernate 导不出；
--   b. actor_authenticated 带 default false：对齐 H2 V8 之后的现状（导出产物只有 not null，
--      默认值是 H2 侧 ALTER 的回填语义，但现状就该有）。
--
-- 共 10 张表 / 5 个索引 / 2 个唯一约束。ddl-auto 仍是 validate，本目录是 PG 侧模式的唯一产生源。

create table audit_event (actor_authenticated boolean not null default false, schema_version integer not null, consumed_at timestamp(6) with time zone not null, id bigint generated by default as identity, occurred_at timestamp(6) with time zone not null, object_type varchar(24) not null, actor varchar(32) not null, tenant_id varchar(32) not null, action varchar(40) not null, event_id varchar(64) not null, object_id varchar(64) not null, detail varchar(255), primary key (id), constraint uk_audit_event_id unique (event_id));
create table coupons (discount_fen bigint not null, id bigint generated by default as identity, threshold_fen bigint not null, status varchar(20) not null, customer_id varchar(32) not null, tenant_id varchar(32) not null, rule_id varchar(64) not null, primary key (id));
create table customers (phone varchar(20) not null, id varchar(32) not null, nickname varchar(64) not null, primary key (id));
create table feedback (created_at timestamp(6) with time zone not null, verdict varchar(8) not null, review_status varchar(12) not null, customer_id varchar(32) not null, tenant_id varchar(32) not null, id varchar(40) not null, ticket_id varchar(40), conversation_id varchar(64) not null, signals varchar(128), reason varchar(512), rule_ids oid, primary key (id));
create table logistics (seq integer not null, id bigint generated by default as identity, occurred_at timestamp(6) with time zone not null, cp_code varchar(32) not null, node_code varchar(32) not null, order_id varchar(32) not null, tenant_id varchar(32) not null, cp_name varchar(64) not null, tracking_no varchar(64) not null, description varchar(255) not null, primary key (id));
create table order_addresses (version integer not null, changed_at timestamp(6) with time zone not null, id bigint generated by default as identity, receiver_phone varchar(20) not null, city varchar(32) not null, district varchar(32) not null, order_id varchar(32) not null, province varchar(32) not null, tenant_id varchar(32) not null, receiver_name varchar(64) not null, detail_address varchar(255) not null, primary key (id));
create table orders (address_version integer not null, amount_fen bigint not null, created_at timestamp(6) with time zone not null, delivered_at timestamp(6) with time zone, paid_at timestamp(6) with time zone, shipped_at timestamp(6) with time zone, receiver_phone varchar(20) not null, status varchar(20) not null check (status in ('CREATED','PAID','SHIPPED','DELIVERED','COMPLETED','CANCELLED','REFUNDING','REFUNDED')), category_code varchar(32) not null, city varchar(32) not null, customer_id varchar(32) not null, district varchar(32) not null, id varchar(32) not null, province varchar(32) not null, tenant_id varchar(32) not null, category_name varchar(64) not null, receiver_name varchar(64) not null, service_flags varchar(128) not null, detail_address varchar(255) not null, primary key (id));
create table refunds (amount_fen bigint not null, created_at timestamp(6) with time zone not null, id bigint generated by default as identity, status varchar(20) not null, customer_id varchar(32) not null, order_id varchar(32) not null, tenant_id varchar(32) not null, ticket_id varchar(40), idempotency_token varchar(64) not null, reason varchar(255) not null, primary key (id), constraint uk_refund_idempotency unique (order_id, idempotency_token));
create table tenants (rate_limit_qps integer not null, id varchar(32) not null, name varchar(64) not null, primary key (id));
create table users (created_at timestamp(6) with time zone not null, role varchar(16) not null check (role in ('BUYER','AGENT','ADMIN')), status varchar(16) not null, id varchar(32) not null, subject_ref varchar(32), tenant_id varchar(32) not null, display_name varchar(64), username varchar(64) not null, password_hash varchar(100) not null, primary key (id), constraint uk_users_tenant_username unique (tenant_id, username));
create index idx_coupon_customer on coupons (customer_id);
create index idx_feedback_review on feedback (review_status, created_at);
create index idx_logistics_order on logistics (order_id);
create index idx_addr_order on order_addresses (order_id);
create index idx_audit_tenant_time on audit_event (tenant_id, occurred_at);
